# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

run:
  timeout: 5m
  modules-download-mode: readonly
  skip-files:
    - ".*\\.gen\\.go$"
  issues-exit-code: 1

linters:
  enable:
    - errcheck
    - goimports
    - golint
    - govet
    - staticcheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  errcheck:
    exclude: errcheck_excludes.txt
